#! /usr/bin/env bash
ASSIGNMENT=/autograder/assignment/Cargo.toml
SUBMISSION=/autograder/submission/Cargo.toml
OUR_TEST_RESULTS=/autograder/our_test_results
THEIR_TEST_RESULTS=/autograder/their_test_results
OUTPUT=/autograder/results/results.json
LCOV=/autograder/submission/ccov/lcov.info
SCORES=/autograder/scores.yaml
OUR_SOLUTION=/autograder/assignment/src/solution.rs
THEIR_SOLUTION=/autograder/submission/src/solution.rs
