#! /usr/bin/env bash
ASSIGNMENT=/autograder/assignment/Cargo.toml
SUBMISSION=/autograder/submission/Cargo.toml
OUTPUT=/autograder/results/results.json
LCOV=/autograder/ccov/lcov.info
SCORES=/autograder/scores.yaml
OUR_SOLUTION=/autograder/assignment/src/solution.rs
THEIR_SOLUTION=/autograder/submission/src/solution.rs
