#! /usr/bin/env bash
set -x
config=${1:-config.sh}
source $config
mkdir outputs/
mkdir results/
for i in $(seq 1 6)
do
  python3 replace_lines.py \
    --from-path submission/src/main.rs \
    --to-path assignment/src/solution.rs \
    --output assignment/src/main.rs \
    --replace-start "// Problem $i: change something here to make this compile:" \
    --replace-end "// Do not change any lines until the next comment"
  cargo build --manifest-path assignment/Cargo.toml > "outputs/$i"
  echo "$?" >> output_codes.txt
done

python3 autograder.py \
  --build-output-paths $(ls -d outputs/*) \
  --scores-path output_codes.txt \
  --output results/results.json
