#! /usr/bin/env bash
set -x
config=${1:-config.sh}
source $config

# create coverage file
ccov=$(dirname $LCOV)
mkdir -p $ccov
cd $(dirname $SUBMISSION)
cargo test
zip -0 $ccov/ccov.zip $(find . \( -name "submission*.gc*" \) -print)
grcov $ccov/ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing -o $LCOV

# run our tests on their solution
cargo test --manifest-path $ASSIGNMENT -- -Z unstable-options --format json >&1 | tee $OUR_TEST_OUTPUTS
if [[ ! -s $OUR_TEST_OUTPUTS ]]; then
	echo "Failed to run our tests on your code. 
1. Check Cargo.toml to make sure you have named your package 'submission'.
2. Check that your solution (the code that we are testing) exists in a file named 'solution.rs'.
3. Check that this file is declared a public module at the top of 'lib.rs': 'pub mod solution;'.
"
	exit
fi

# run their tests on our solution
cp $OUR_SOLUTION $THEIR_SOLUTION
cargo clean --manifest-path $SUBMISSION
cargo test --manifest-path $SUBMISSION -- -Z unstable-options --format json >&1 | tee $THEIR_TEST_OUTPUTS

# process into results.json
mkdir -p $(dirname $OUTPUT)
cargo run --manifest-path $AUTOGRADER -- \
	--our-test-outputs=$OUR_TEST_OUTPUTS \
	--their-test-outputs=$THEIR_TEST_OUTPUTS \
	--submission=$SUBMISSION \
	--output=$OUTPUT \
	--lcov=$LCOV \
	--scores=$SCORES \
	--labels=$LABELS
